### ISSUE TITLE
API Endpoint Interface Improvements.

### ISSUE THREAD

**Issue by souravbadami** [betafactory/MarsRoverAndroid#1]
`MarsRoverAndroid/app/src/main/java/com/androidyug/marsrover/data/rest/ApiEndpointInterface.java` has three methods:

- **getPhotoByCuriosity**
- **getPhotoBySpirit**
- **getPhotoByOpportunity**

All of them resembles in terms of signature and rest call pattern. How about clubbing them into a single generic method ?

/cc @nitinnatural.

**Comment by AliAzaz** [comment]
I'm picking this up

**Comment by souravbadami** [comment]
@AliAzaz -- Sure! Assigned.

**Comment by nitinnatural** [comment]
@AliAzaz Thanks. Your PR is accepted and merged.

**Comment by AliAzaz** [comment]
Thanks
