### ISSUE TITLE
Kotlinify it.

### ISSUE THREAD

**Issue by nitinnatural** [betafactory/MarsRoverAndroid#4]
Right now the codebase is in java. Need to migrate to Kotlin.

**Comment by AliAzaz** [comment]
Let me pick this one

**Comment by nitinnatural** [comment]
@AliAzaz  sure go-ahead

**Comment by souravbadami** [comment]
@AliAzaz -- Assigned you. It would be great if you break down the problem into smaller tasks, list them in this issue thread and start working from there.

**Comment by AliAzaz** [comment]
Yes sure. Currently fragments and activities converted to kotlin. Working on ViewPager class

**Comment by nitinnatural** [comment]
@AliAzaz  merged!! Thanks man.
